---
- hosts: '{{ hosts }}'
  gather_facts: false
  connection: local
  vars:
   user: 'awx'
   password: 'qw583H&bBE5qYKAy'
 
  tasks:
  - name: Check if port 23 is listening
    wait_for:
        port: 23
        host: '{{ansible_host}}'
        delay: 2
        timeout: 5
        msg: "Timeout waiting for 23 to respond"
    register: port_check
    ignore_errors: yes
    
  - name: Executing the expect script
    script: ./script/get_commands.expect '{{ ansible_host }}' '{{ user }}' '{{ password }}' ./script/show-version.txt
    when: port_check.failed == false
    register: expect_out
